// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_RESPONSE = 'FETCH_POSTS_RESPONSE';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const ENABLE_LOADER_POSTS = 'ENABLE_LOADER_POSTS';
export const DISABLE_LOADER_POSTS = 'DISABLE_LOADER_POSTS';
